# Generated by Django 3.2.4 on 2021-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchAndTag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='abstract',
            new_name='Abstract',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='doi',
            new_name='Doi',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='pubDate',
            new_name='PubDate',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='authors',
            new_name='PubmedID',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='keywords',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='name',
            new_name='Affiliation',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='surname',
            new_name='Surname',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='pubmedID',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='title',
        ),
        migrations.AddField(
            model_name='articles',
            name='Authors',
            field=models.ManyToManyField(blank=True, to='searchAndTag.Authors'),
        ),
        migrations.AddField(
            model_name='authors',
            name='Name',
            field=models.TextField(default='NAME'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=254)),
                ('Articles', models.ManyToManyField(blank=True, to='searchAndTag.Articles')),
                ('Tag', models.ManyToManyField(blank=True, to='searchAndTag.Tags')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='Keywords',
            field=models.ManyToManyField(blank=True, to='searchAndTag.Keywords'),
        ),
        migrations.AddField(
            model_name='articles',
            name='Tags',
            field=models.ManyToManyField(blank=True, to='searchAndTag.Tags'),
        ),
    ]
