# Generated by Django 3.2.4 on 2021-06-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchAndTag', '0006_auto_20210621_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Authors',
            field=models.ManyToManyField(blank=True, to='searchAndTag.Authors'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='Keyword',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='users',
            name='Articles',
            field=models.ManyToManyField(blank=True, to='searchAndTag.Articles'),
        ),
    ]
