# Generated by Django 3.2.4 on 2021-06-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchAndTag', '0008_auto_20210621_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Authors',
            field=models.ManyToManyField(blank=True, null=True, to='searchAndTag.Authors'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Doi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='PubDate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='PubmedID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='Name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='Surname',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='Keyword',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='Link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Articles',
            field=models.ManyToManyField(blank=True, to='searchAndTag.Articles'),
        ),
    ]
